### PR TITLE
support XMLHttpRequest.withCredentials

### PR DESCRIPTION
**Pull request by mikegolod**

### CODE REVIEW

**Comment by mikegolod** [comment]
I think that way is kinda weird. Must write a func to do simple things that can be request options (just like in axios).

**Comment by zackify** [comment]
@mikegolod yes, but at the same time we cant support every option ever that xhr has, and making our own api around it gets messy. I think it's worth adding the fields and headers abstraction. I think I'll merge this and if there's more like this we will just expose the xhr instance before the request

**Comment by mikegolod** [comment]
Thx! Sure we can abstract higher if there'll be cases. But I think that handling CORS in dev is more common than any other case.

**Comment by zackify** [comment]
it's up as 3.0.2

**Comment by mikegolod** [comment]
Thank you!

**Pull request merged**
