### PR TITLE
reset state when a new upload begins

### PR DESCRIPTION
**Pull request by ingro**
That should keep the ui consistent when a new upload starts after a first successfully one.

### CODE REVIEW

**Comment by zackify** [comment]
Thanks. I'll throw in a check to only set the state if the progress isn't 0.1 so that we don't call set state for no reason on the first upload and make a new release!

**Comment by ingro** [comment]
Oh right, that makes sense :)

**Comment by zackify** [comment]
It's out as 3.0.4!

**Comment by ingro** [comment]
Cool, thanks for the quick release!

**Pull request merged**
